CollectiveList/urls.py
"""
CollectiveList.urls - CollectiveList URL Configuration
Copyright (C) 2020 >make Utopia_

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from django.contrib import admin
from django.urls import include, path
from CollectiveList import settings
from django.conf.urls.static import static
from . import views

admin.site.site_header = 'KollektivListe Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('impressum/', views.ImpressumPageView.as_view(), name='impressum'),
    path('kontakt/', views.ContactPageView.as_view(), name='kontakt'),
    path('newsletter/', views.NewsletterPageView.as_view(), name='newsletter'),
    path('links/', views.LinksPageView.as_view(), name='links'),
    path('tinymce/', include('tinymce.urls')),
    path('', include('collectives.urls')),
    path('', include('offers.urls')),
    path('', include('events.urls')),
    path('', views.HomePageView.as_view(), name='startseite')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
"""
events.urls - url registration for events
Copyright (C) 2020 >make Utopia_

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from django.urls import path
from . import views

urlpatterns = [
    path('event/list/', views.EventListView.as_view(), name='event_list'),
    path('event/new/', views.EventCreateView.as_view(), name='event_new'),
    path('event/<int:pk>/update/', views.EventUpdateView.as_view(),
         name='event_update'),
    path('event/<int:pk>/delete/', views.EventDeleteView.as_view(),
         name='event_delete'),
]

collectives/models.py
"""
collectives.models - Database model for Collective
Copyright (C) 2020 >make Utopia_

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField


class BusinessClass(models.Model):
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='children')
    name = models.CharField(
        max_length=50,
        verbose_name="Branche",
        unique=True)

    class Meta:
        verbose_name = 'Branche'
        verbose_name_plural = 'Branchen'

    def getAllParents(self):
        parent = self.parent
        parentList = []
        while parent is not None:
            parentList.append(parent)
            parent = parent.parent
        return parentList
    
    def gellAllChildren(self, child = None):
        if child is None:
            children = self.children.all()
        else:
            children = child.children.all()
        childList = list(children)
        for child in children:
            childList += self.gellAllChildren(child)
        return childList

    def __str__(self):
        """A string representation of the model."""
        return f"{'- ' * len(self.getAllParents())}{self.name}"

    def getFullString(self):
        ret = ""
        for p in reversed(self.getAllParents()):
            ret += f"{p.name}/"
        ret += f"{self.name}"
        return ret


class Collective(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Name des Kollektivs")
    title = models.CharField(
        max_length=200,
        blank=True,
        verbose_name="Beschreibung (Stichworte)")
    logo = models.ImageField(
        "euer logo",
        blank=True,
        null=True,
        upload_to='logos')
    bgpic = models.ImageField(
        "Euer Hintergrundbild (Es sollte im Querformat und nicht mehr als 2MB groß sein.)",
        blank=True,
        null=True,
        upload_to='bgpics')
    description = HTMLField(
        blank=True,
        verbose_name="Ausführliche Beschreibung")
    website = models.URLField(
        blank=True,
        max_length=100,
        verbose_name="Webseite")
    email = models.EmailField(
        blank=True,
        max_length=100,
        verbose_name="Email")
    businessClassList = models.ManyToManyField(BusinessClass, verbose_name="Branchen")
    last_editor = models.ForeignKey(
        'accounts.User',
        null=True,
        on_delete=models.SET_NULL)
    last_edit_time = models.DateTimeField(
        auto_now=True,
        null=True)
    public = models.BooleanField(
        default=False,
        verbose_name='veröffentlichen')
    authors = models.ManyToManyField(
        'accounts.User',
        related_name="AuthorInnen",
        verbose_name='Author*innen')

    class Meta:
        ordering = ["name"]
        verbose_name = "Kollektiv"
        verbose_name_plural = "Kollektive"

    def __str__(self):
        """A string representation of the model."""
        return self.name[:50]

    def get_absolute_url(self):
        return reverse('collective_detail', args=[str(self.id)])


class KdKMember(models.Model):
    collective = models.ForeignKey(Collective, on_delete=models.CASCADE)
    since = models.DateField(verbose_name="Mitglied seit")
    till = models.DateField(verbose_name="Mitglied bis", blank=True, null=True)
    
    class Meta:
        verbose_name = 'KdK Mitglied'
        verbose_name_plural = 'KdK Mitglieder'

    def __str__(self):
        """A string representation of the model."""
        bis = ""
        if self.till is not None:
            bis = f" bis {self.till:%d.%m.%Y}"
        return f"{self.collective.name[:50]} seit {self.since:%d.%m.%Y}{bis}"

        
class AdditionalAddress(models.Model):
    collective = models.ForeignKey(Collective, on_delete=models.CASCADE, related_name='addresses')
    address = models.CharField(
        blank=True,
        max_length=256,
        verbose_name="Straße und Hausnummer")
    postal_code = models.CharField(
        blank=True,
        max_length=5,
        verbose_name="PLZ")
    city = models.CharField(
        blank=False,
        max_length=50,
        verbose_name="Stadt")
    country = models.CharField(
        blank=True,
        max_length=100,
        default="Deutschland",
        verbose_name="Land")
    lat = models.DecimalField(
        blank=True,
        max_digits=9,
        decimal_places=6,
        null=True)
    lon = models.DecimalField(
        blank=True,
        max_digits=9,
        decimal_places=6,
        null=True)
    current = models.BooleanField(
        default=False,
        verbose_name='Aktuelle Adresse')

    class Meta:
        verbose_name = 'Adresse'
        verbose_name_plural = 'Adressen'

    def __str__(self):
        """A string representation of the model."""
        return f"{self.collective.name[:50]}\n{self.address}\n{self.postal_code} {self.city}"

class CheckResultClass(models.Model):
    name = models.CharField(
        primary_key=True,
        max_length=20)

    class Meta:
        verbose_name = 'Prüfungs Ergebnis'
        verbose_name_plural = 'Prüfungs Ergebnisse'

    def __str__(self):
        """A string representation of the model."""
        return f"{self.name}"
        
class Checked(models.Model):
    collective = models.ForeignKey(Collective, on_delete=models.CASCADE)
    checker = models.ForeignKey(
        'accounts.User',
        null=True,
        on_delete=models.SET_NULL)
    checktime = models.DateTimeField(
        auto_now_add=True,
        null=True)
    result = models.ForeignKey(CheckResultClass, on_delete=models.CASCADE, verbose_name='Ergebnis')

    class Meta:
        verbose_name = 'Überprüft'
        verbose_name_plural = 'Überprüfungen'

    def __str__(self):
        """A string representation of the model."""
        return f"{self.collective.name[:50]} {self.checktime:%d.%m.%Y}:{self.result}"

    

events/models.py
"""
events.models - Database model for Event
Copyright (C) 2020 >make Utopia_

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField 


class Event(models.Model):
    title = models.CharField(
        max_length=200,
        default="",
        verbose_name="Titel")
    description = HTMLField(
        blank=True,
        default="",
        verbose_name="Beschreibung")
    start_date = models.DateField(
        verbose_name="Datum")
    start_time = models.TimeField(
        blank=True,
        null=True,
        verbose_name="Beginn")
    center_name = models.CharField(
        max_length=200,
        default="",
        verbose_name="Name des Veranstaltungsortes")
    social_media_site = models.URLField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="Social Media Seite der Veranstaltung")
    collective = models.ForeignKey(
        'collectives.Collective',
        related_name="events",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name="Kollektiv")
    provider = models.CharField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="Veranstalter (nur eintragen, wenn verschieden vom Kollektiv)")
    website = models.URLField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="Webseite (nur eintragen, wenn verschieden vom Kollektiv)")
    email = models.EmailField(
        blank=True,
        default="",
        verbose_name="E-Mail-Adresse (nur eintragen, wenn verschieden vom Kollektiv)")
    address = models.CharField(
        blank=True,
        max_length=256,
        verbose_name="Straße und Hausnummer (nur eintragen, wenn verschieden vom Kollektiv)")
    postal_code = models.CharField(
        blank=True,
        max_length=5,
        verbose_name="Postleitzahl (nur eintragen, wenn verschieden vom Kollektiv)")
    city = models.CharField(
        blank=True,
        max_length=50,
        verbose_name="Stadt (nur eintragen, wenn verschieden vom Kollektiv)")
    country = models.CharField(
        blank=True,
        max_length=100,
        default="Deutschland",
        verbose_name="Land")
    lat = models.DecimalField(
        blank=True,
        max_digits=9,
        decimal_places=6,
        null=True)
    lon = models.DecimalField(
        blank=True,
        max_digits=9,
        decimal_places=6,
        null=True)
    author = models.ForeignKey(
        'accounts.User',
        null=True,
        on_delete=models.SET_NULL)
    modified_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["start_date"]
        verbose_name = "Veranstaltung"
        verbose_name_plural = "Veranstaltungen"

    def __str__(self):
        """A string representation of the model."""
        return self.title[:100]

    def get_absolute_url(self):
        return reverse('event_detail', args=[str(self.id)])

offers/models.py
"""
offers.models - Database model for Offer
Copyright (C) 2020 >make Utopia_

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField


class Offer(models.Model):
    sort = models.CharField(
        max_length=7,
        default="",
        choices=[("Angebot", "Angebot"), ("Gesuch", "Gesuch")],
        verbose_name="Art")
    title = models.CharField(
        max_length=200,
        default="",
        verbose_name="Titel")
    description = HTMLField(
        default="",
        verbose_name="Beschreibung")
    collective = models.ForeignKey(
        'collectives.Collective',
        related_name="offers",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name="Kollektiv")
    provider = models.CharField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="Anbieter (nur eintragen, wenn verschieden vom Kollektiv)")
    website = models.URLField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="Webseite (nur eintragen, wenn verschieden vom Kollektiv)")
    email = models.EmailField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="E-Mail-Adresse (nur eintragen, wenn verschieden vom Kollektiv)")
    address = models.CharField(
        blank=True,
        max_length=256,
        verbose_name="Straße und Hausnummer (nur eintragen, wenn verschieden vom Kollektiv)")
    postal_code = models.CharField(
        blank=True,
        max_length=5,
        verbose_name="Postleitzahl (nur eintragen, wenn verschieden vom Kollektiv)")
    city = models.CharField(
        blank=True,
        max_length=50,
        verbose_name="Stadt (nur eintragen, wenn verschieden vom Kollektiv)")
    country = models.CharField(
        blank=True,
        max_length=100,
        default="Deutschland",
        verbose_name="Land (nur eintragen, wenn verschieden vom Kollektiv)")
    lat = models.DecimalField(
        blank=True,
        max_digits=9,
        decimal_places=6,
        null=True)
    lon = models.DecimalField(
        blank=True,
        max_digits=9,
        decimal_places=6,
        null=True)
    author = models.ForeignKey(
        'accounts.User',
        null=True,
        on_delete=models.SET_NULL)
    modified_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["modified_time"]
        verbose_name = "Anzeige"
        verbose_name_plural = "Anzeigen"

    def __str__(self):
        """A string representation of the model."""
        return self.title[:100]

    def get_absolute_url(self):
        return reverse('offer_detail', args=[str(self.id)])

CollectiveList/forms.py
"""
CollectiveList.forms - Contact form for CollectiveList views
Copyright (C) 2020 >make Utopia_

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from django import forms


class ContactForm(forms.Form):
    receiver = forms.CharField(
        label="Empfänger",
        required=False,
        widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    sender = forms.EmailField(label="Deine E-Mail-Adresse", required=True)
    subject = forms.CharField(label="Betreff", required=True)
    text = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'materialize-textarea'}),
        label="Deine Nachricht",
        required=True
    )


class NewsletterForm(forms.Form):
    sender = forms.EmailField(label="Deine E-Mail-Adresse", required=True)

templates/base.html
{% load static %}
<!doctype html>
<html lang="de">
  <head>
    <title>Kollektivliste.org</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut_icon" href="{% static 'icons/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'icons/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://kollektivliste.b-cdn.net{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="https://kollektivliste.b-cdn.net{% static 'css/custom-style.css' %}">
    <script src="https://kollektivliste.b-cdn.net{% static 'js/polyfills.js' %}"></script>
  {% if "/offer/" in request.get_full_path %}
    <link rel="stylesheet" href="https://kollektivliste.b-cdn.net{% static 'css/custom-offers-style.css' %}">
  {% elif "/event/" in request.get_full_path %}
    <link rel="stylesheet" href="https://kollektivliste.b-cdn.net{% static 'css/custom-events-style.css' %}">
  {% else %}
    <link rel="stylesheet" href="https://kollektivliste.b-cdn.net{% static 'css/custom-collectives-style.css' %}">
  {% endif %}
  </head>
  <body>
    <header class="navbar-fixed">
      <!-- Dropdown Structure -->
      <ul id="dropdown-editactions1" class="dropdown-content navbar-content">
      {% if my_collectives %}
        <li class="dropdown-headline">Mein Kollektiv bearbeiten:</li>
        {% for my_c in my_collectives %}
        <li><a class="dropdown-item" href="/collective/{{ my_c.id }}/update/">{{ my_c.name }}</a></li>
        {% endfor %}
        <li class="divider"></li>
      {% endif%}
      {% if user.is_staff %}
        <li><a class="dropdown-item" href="{% url 'add_user' %}">Autor eintragen</a></li>
        <li class="divider"></li>
        <li><a class="dropdown-item" href="{% url 'collective_new' %}">Kollektiv eintragen</a></li>
        <li class="divider"></li>
      {% endif %}
        <li><a class="dropdown-item" href="{% url 'offer_new' %}">Anzeige eintragen</a></li>
        <li class="divider"></li>
        <li><a class="dropdown-item" href="{% url 'event_new' %}">Termin eintragen</a></li>
      </ul>
      <ul id="dropdown-useractions1" class="dropdown-content navbar-content">
        <li><a class="dropdown-item" href="{% url 'password_change' %}">Passwort ändern</a></li>
        <li class="divider"></li>
        <li><form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button class="dropdown-item" type="submit">logout</button>
          </form>
        </li>
      </ul>
      <!-- Nav from materialize, fixed by custom js to use only one tag for moble sidenav and desktop -->
      <nav class="{{ request.app_config.bg_color }}">
        <div class="container">
          <div class="nav-wrapper">
            <a href="{% url 'startseite' %}" class="brand-logo">Kollektivliste.org</a>
            <a href="#" data-activates="mobile-nav" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li class="{% if request.get_full_path == "/collective/list/" %}active{% endif %}">
                <a href="{% url 'collective_list' %}" title="Alle Kollektive filterbar nach Branche und Region">Kollektive</a>
              </li>
              <li class="{% if request.get_full_path == "/collective/map/" %}active{% endif %}">
                <a href="{% url 'collective_map' %}" title="Alle Kollektive auf einer Karte anzeigen">Karte</a>
              </li>
              <li class="{% if request.get_full_path == "/event/list/" %}active{% endif %}">
                <a href="{% url 'event_list' %}" title="Termine einzelner Kollektive oder übergreifender Veranstaltungen">Termine</a>
              </li>
              <li class="{% if request.get_full_path == "/offer/list/" %}active{% endif %}">
                <a href="{% url 'offer_list' %}" title="Angebote und Gesuche beteiligter Kollektive">Marktplatz</a>
              </li>
              <li class="{% if request.get_full_path == "/kontakt/" %}active{% endif %}">
                <a href="{% url 'kontakt' %}" title="Nimm Kontakt mit uns oder einem Kollektiv aus der Liste auf">Kontakt</a>
              </li>
              <li class="{% if request.get_full_path == "/newsletter/" %}active{% endif %}">
                <a href="{% url 'newsletter' %}" title="Abonniere den Newsletter um über alle Neuigkeiten rund um die Kollektive informiert zu bleiben">Newsletter</a>
              </li>
            <!-- Dropdown Trigger -->
            {% if user.is_authenticated %}
            {% with '/collective/new/ /offer/new/ /event/new/' as edit_list %}
              <li class="{% if request.get_full_path in edit_list.split or "update" in request.get_full_path %}active{% endif %}">
                <a id="editactions1" class="dropdown-button" href="#!" data-activates="dropdown-editactions1">
                  {{ ddval|default:"bearbeiten" }}
                  <i class="material-icons right">arrow_drop_down</i></a>
              </li>
            {% endwith %}
              <li class="{% if "password" or "logout" in request.get_full_path %} active{% endif %}">
                <a id="useractions1" class="dropdown-button" href="#!" data-activates="dropdown-useractions1">
                {% if request.get_full_path == "/accounts/password_change/" %}Profil{% else %}{{ user.email }}{% endif %}
                  <i class="material-icons right">arrow_drop_down</i></a>
              </li>
            {% else %}
              <li class="{% if "accounts" in request.get_full_path %} active{% endif %}">
                <form>
                  <a href="{% url 'login' %}" class="btn btn-outline-secondary">Login</a>
                </form>
              </li>
            {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    {% block content %}
    {% endblock content %}
    </main>

    <footer class="page-footer {{ request.app_config.bg_color }}">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <p><a href="{% url 'about' %}">Was ist das hier?</a><br>
            <a href="{% url 'links' %}">Links</a></p>
          </div>
          <div class="col l6 s12 right-align">
            <p><a href="{% url 'impressum' %}">Impressum / Datenschutzerklärung</a></p>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              © 2020 >make Utopia_, 2024 Kollektiv der Kollektive (KdK)
            </div>
            <div class="col l6 s12 right-align">
              created by <a href="https://www.makeutopia.de/">>make Utopia_</a>,
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
  <script src="https://kollektivliste.b-cdn.net{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="https://kollektivliste.b-cdn.net{% static 'js/materialize.min.js' %}"></script>
  <script src="https://kollektivliste.b-cdn.net{% static 'js/custom-scripts.js' %}"></script>
</html>

templates/collective_new.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <h2>Ein Kollektiv anlegen</h2>
    <form action="" method="post" class="col s12">
      {% csrf_token %}
      {{ form.media }}
      {{ form|crispy }}
      <button class="btn usedit" type="submit">Speichern</button>
      <button class="btn" type="reset">Zurücksetzen</button>
      <a href="{% url 'collective_list' %}" class="btn">Abbrechen</a>
    </form>
  </div>
</div>
{% endblock %}

templates/event_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h1>Veranstaltung löschen</h1>
    <form action="" method="post">
      {% csrf_token %}
      <p>Willst du wirklich die Veranstaltung "{{ event.title }}" löschen?</p>
      <button class="btn usedanger" type="submit">Ja, ich will den Eintrag löschen.</button>
      <a href="{% url 'event_list' %}" class="btn"
          type="button">Abbrechen</a>
    </form>
  </div>
</div>
{% endblock %}

templates/event_list.html
{% extends 'base_full.html' %}
{% block content %}
<div class="hero-image">
  <h1 class="hero-headline white-text drop-shadow">Veranstaltungskalender</h1>
</div>
<div class="container">
  <div class="row">
  {% if object_list %}
  {% for event in object_list %}
    <div id="{{ event.id }}" class="col s12">
      <div class="card hoverable">
        <div class="card-panel {{ request.app_config.bg_color }} white-text">
          <div class="card-title">{{ event.start_date|date:'d.m.Y' }}, {{ event.city }}: {{ event.title }}</div>
        </div>
        <div class="card-content">
          <p>
            {{ event.description|safe }}
          </p>
          <br>
          <p>
            <strong>Ort:</strong> {{ event.center_name }}, {{ event.address }}, {{ event.postal_code }} {{ event.city }}<br>
            <strong>Zeit:</strong> {{ event.start_date }}, {{ event.start_time|default_if_none:"" }}
          </p>
          {% if event.collective %}
          <p>
            <strong>Veranstaltendes Kollektiv:</strong> <a href="{% url 'collective_detail' event.collective.pk %}" class="related_collective">{{ event.collective.name }}</a>
          </p>
          {% endif %}
        </div>
        <div class="card-action">
          <div class="row">
            <div class="col s6">
              <a href="{{ event.website }}">Webseite</a>
            </div>
            <div class="col s6">
              <a href="{{ event.social_media_site }}">Social Media Site</a>
            </div>
          </div>
        </div>
        <div class="card-content">
          {% if perms.events.change_event or user == event.author %}
          <div class="right-align">
            <a class="btn usedit" href="{% url 'event_update' event.pk %}" role="button">Eintrag bearbeiten</a>
            <a class="btn usedanger" href="{% url 'event_delete' event.pk %}">Eintrag löschen</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
  {% else %}
    <div class="col s12 card no-content-box white-text">
      <h3>Momentan sind keine Veranstaltungen vorhanden.</h3>
    </div>
  {% endif %}
  </div>
</div>
{% endblock content %}

templates/event_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="row">
    <form action="" class="col s12" method="post">
      {% csrf_token %}
      {{ form.media }}
      {{ form|crispy }}
      <button class="btn usedit" type="submit">Speichern</button>
      <button class="btn" type="reset">Zurücksetzen</button>
      <a href="{% url 'event_list' %}" class="btn">Abbrechen</a>
    </form>
  </div>
</div>
{% endblock %}

templates/offer_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h1>Angebot löschen</h1>
    <form action="" method="post">
      {% csrf_token %}
      <p>Willst du wirklich den Eintrag für das Angebot "{{ offer.name }}" löschen?</p>
      <button class="btn usedanger" type="submit">Ja, ich will den Eintrag löschen.</button>
      <a href="{% url 'offer_list' %}" class="btn"
          type="button">Abbrechen</a>
    </form>
  </div>
</div>
{% endblock %}